import { constants as fsConstants } from "node:fs"
import fs from "node:fs/promises"
import path from "node:path"
import { fileURLToPath } from "node:url"

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..")
const quartzSourcePath = path.join(repoRoot, "quartz")
const targetPath = path.join(repoRoot, "node_modules", "@jackyzha0", "quartz", "quartz")
const markerPath = path.join(quartzSourcePath, ".learning-machine-generated")
const customStylePath = path.join(quartzSourcePath, "styles", "custom.scss")

try {
  await fs.access(targetPath, fsConstants.R_OK)
} catch {
  console.warn("Quartz dependency is not installed yet; skipping Quartz source copy.")
  process.exit(0)
}

try {
  const stat = await fs.lstat(quartzSourcePath)
  if (stat.isSymbolicLink()) {
    await fs.unlink(quartzSourcePath)
  } else if (stat.isDirectory()) {
    await fs.access(markerPath, fsConstants.R_OK)
    await fs.rm(quartzSourcePath, { recursive: true, force: true })
  } else {
    throw new Error(`${quartzSourcePath} exists and is not a generated directory`)
  }
} catch (error) {
  if (error.code !== "ENOENT") {
    throw error
  }
}

await fs.cp(targetPath, quartzSourcePath, { recursive: true })
await fs.appendFile(
  customStylePath,
  `
/* Learning Machine lessons export */
.lessons-topic-index + .page-listing {
  display: none;
}
`,
)
await fs.writeFile(markerPath, "Generated by scripts/link_quartz.mjs.\n")
console.log(`Copied Quartz source to ${path.relative(repoRoot, quartzSourcePath)}`)
